name: Palletizer
uph: 13000
buffer_capacity: 40

reliability:
  mtbf_min: 480
  mttr_min: null

performance:
  jam_prob: 0.0
  jam_time_sec: 0

quality:
  defect_rate: 0.0
  detection_prob: 0.0

cost_rates:
  labor_per_hour: 20.00      # Highly automated
  energy_per_hour: 4.00      # Robotics
  overhead_per_hour: 8.00    # Low maintenance
