slice_name: Production Over Time
description: Pallets produced over time (time series)
viz_type: echarts_timeseries_line
params:
  datasource: 10000000-0000-0000-0000-000000000003__table
  viz_type: echarts_timeseries_line
  x_axis: ts
  time_grain_sqla: PT5M
  metrics:
    - sum_pallets
  groupby: []
  row_limit: 10000
  order_desc: false
  rich_tooltip: true
  tooltipTimeFormat: '%Y-%m-%d %H:%M'
  x_axis_title: Time
  y_axis_title: Pallets Produced
  y_axis_format: ',.0f'
  show_legend: false
  legendOrientation: top
  color_scheme: supersetColors
  markerEnabled: false
  zoomable: true
  extra_form_data: {}
cache_timeout: null
uuid: 20000000-0000-0000-0000-000000000009
version: 1.0.0
dataset_uuid: 10000000-0000-0000-0000-000000000003
